packages:
  - docs
  - packages/*

catalog:
  '@antfu/ni': ^27.0.0
  '@antfu/utils': ^9.3.0
  '@iconify-json/carbon': ^1.2.14
  '@iconify-json/logos': ^1.2.9
  '@iconify-json/svg-spinners': ^1.2.4
  '@shikijs/vitepress-twoslash': ^3.13.0
  '@types/node': ^24.9.1
  '@unocss/reset': ^66.5.4
  '@vueuse/core': ^14.0.0
  bumpp: ^10.3.1
  chinese-simple2traditional: ^2.2.2
  floating-vue: ^5.2.2
  lint-staged: ^16.2.6
  markdown-it-mathjax3: ^5.2.0
  oxfmt: ^0.8.0
  oxlint: ^1.24.0
  oxlint-tsgolint: ^0.2.1
  pinia: ^3.0.3
  pnpm: ^10.19.0
  sass-embedded: ^1.93.2
  simple-git-hooks: ^2.13.1
  tsx: ^4.20.6
  typescript: ^5.9.3
  unbuild: ^3.6.1
  unocss: ^66.5.4
  unplugin-vue-components: ^30.0.0
  vite: ^7.1.12
  vite-tsconfig-paths: ^5.1.4
  vitepress: 2.0.0-alpha.12
  vitepress-plugin-group-icons: ^1.6.5
  vitest: ^4.0.2
  vue: ^3.5.22
